/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AnalyticsResult model module.
 * @module model/AnalyticsResult
 * @version 1.0.0
 */
class AnalyticsResult {
    /**
     * Constructs a new <code>AnalyticsResult</code>.
     * @alias module:model/AnalyticsResult
     */
    constructor() { 
        
        AnalyticsResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AnalyticsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnalyticsResult} obj Optional instance to populate.
     * @return {module:model/AnalyticsResult} The populated <code>AnalyticsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnalyticsResult();

            if (data.hasOwnProperty('bin_centers')) {
                obj['bin_centers'] = ApiClient.convertToType(data['bin_centers'], ['Number']);
            }
            if (data.hasOwnProperty('bin_width')) {
                obj['bin_width'] = ApiClient.convertToType(data['bin_width'], 'Number');
            }
            if (data.hasOwnProperty('new_users')) {
                obj['new_users'] = ApiClient.convertToType(data['new_users'], ['Number']);
            }
            if (data.hasOwnProperty('conversations')) {
                obj['conversations'] = ApiClient.convertToType(data['conversations'], ['Number']);
            }
            if (data.hasOwnProperty('user_messages')) {
                obj['user_messages'] = ApiClient.convertToType(data['user_messages'], ['Number']);
            }
            if (data.hasOwnProperty('bot_messages')) {
                obj['bot_messages'] = ApiClient.convertToType(data['bot_messages'], ['Number']);
            }
            if (data.hasOwnProperty('total_messages')) {
                obj['total_messages'] = ApiClient.convertToType(data['total_messages'], ['Number']);
            }
            if (data.hasOwnProperty('sessions_per_user')) {
                obj['sessions_per_user'] = ApiClient.convertToType(data['sessions_per_user'], ['Number']);
            }
            if (data.hasOwnProperty('conversation_length')) {
                obj['conversation_length'] = ApiClient.convertToType(data['conversation_length'], ['Number']);
            }
            if (data.hasOwnProperty('conversation_steps')) {
                obj['conversation_steps'] = ApiClient.convertToType(data['conversation_steps'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * Timestamps of bin_centers
 * @member {Array.<Number>} bin_centers
 */
AnalyticsResult.prototype['bin_centers'] = undefined;

/**
 * Width of each bin in seconds
 * @member {Number} bin_width
 */
AnalyticsResult.prototype['bin_width'] = undefined;

/**
 * Number of new users
 * @member {Array.<Number>} new_users
 */
AnalyticsResult.prototype['new_users'] = undefined;

/**
 * Number of active conversations
 * @member {Array.<Number>} conversations
 */
AnalyticsResult.prototype['conversations'] = undefined;

/**
 * Number of user messages
 * @member {Array.<Number>} user_messages
 */
AnalyticsResult.prototype['user_messages'] = undefined;

/**
 * Number of bot messages
 * @member {Array.<Number>} bot_messages
 */
AnalyticsResult.prototype['bot_messages'] = undefined;

/**
 * Total number of user and bot messages
 * @member {Array.<Number>} total_messages
 */
AnalyticsResult.prototype['total_messages'] = undefined;

/**
 * Average number of sessions per user
 * @member {Array.<Number>} sessions_per_user
 */
AnalyticsResult.prototype['sessions_per_user'] = undefined;

/**
 * Average conversation length
 * @member {Array.<Number>} conversation_length
 */
AnalyticsResult.prototype['conversation_length'] = undefined;

/**
 * Average number of conversation steps
 * @member {Array.<Number>} conversation_steps
 */
AnalyticsResult.prototype['conversation_steps'] = undefined;






export default AnalyticsResult;

