/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BotEvent model module.
 * @module model/BotEvent
 * @version 1.0.0
 */
class BotEvent {
    /**
     * Constructs a new <code>BotEvent</code>.
     * @alias module:model/BotEvent
     */
    constructor() { 
        
        BotEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BotEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BotEvent} obj Optional instance to populate.
     * @return {module:model/BotEvent} The populated <code>BotEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BotEvent();

            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('is_flagged')) {
                obj['is_flagged'] = ApiClient.convertToType(data['is_flagged'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BotEvent.EventEnum} event
 */
BotEvent.prototype['event'] = undefined;

/**
 * @member {Object} data
 */
BotEvent.prototype['data'] = undefined;

/**
 * @member {String} text
 */
BotEvent.prototype['text'] = undefined;

/**
 * @member {Number} timestamp
 */
BotEvent.prototype['timestamp'] = undefined;

/**
 * True if message was flagged.
 * @member {Boolean} is_flagged
 * @default false
 */
BotEvent.prototype['is_flagged'] = false;





/**
 * Allowed values for the <code>event</code> property.
 * @enum {String}
 * @readonly
 */
BotEvent['EventEnum'] = {

    /**
     * value: "bot"
     * @const
     */
    "bot": "bot"
};



export default BotEvent;

