/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BotMessageAttachement model module.
 * @module model/BotMessageAttachement
 * @version 1.0.0
 */
class BotMessageAttachement {
    /**
     * Constructs a new <code>BotMessageAttachement</code>.
     * @alias module:model/BotMessageAttachement
     */
    constructor() { 
        
        BotMessageAttachement.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BotMessageAttachement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BotMessageAttachement} obj Optional instance to populate.
     * @return {module:model/BotMessageAttachement} The populated <code>BotMessageAttachement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BotMessageAttachement();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Attachement caption
 * @member {String} title
 */
BotMessageAttachement.prototype['title'] = undefined;

/**
 * Attachement payload
 * @member {String} payload
 */
BotMessageAttachement.prototype['payload'] = undefined;






export default BotMessageAttachement;

