/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BotMessageAttachement from './BotMessageAttachement';
import BotMessageButtons from './BotMessageButtons';

/**
 * The BotMessage model module.
 * @module model/BotMessage
 * @version 1.0.0
 */
class BotMessage {
    /**
     * Constructs a new <code>BotMessage</code>.
     * @alias module:model/BotMessage
     */
    constructor() { 
        
        BotMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BotMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BotMessage} obj Optional instance to populate.
     * @return {module:model/BotMessage} The populated <code>BotMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BotMessage();

            if (data.hasOwnProperty('recipient_id')) {
                obj['recipient_id'] = ApiClient.convertToType(data['recipient_id'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('buttons')) {
                obj['buttons'] = ApiClient.convertToType(data['buttons'], [BotMessageButtons]);
            }
            if (data.hasOwnProperty('attachement')) {
                obj['attachement'] = ApiClient.convertToType(data['attachement'], [BotMessageAttachement]);
            }
        }
        return obj;
    }


}

/**
 * Id of the message receiver
 * @member {String} recipient_id
 */
BotMessage.prototype['recipient_id'] = undefined;

/**
 * Message
 * @member {String} text
 */
BotMessage.prototype['text'] = undefined;

/**
 * Image URL
 * @member {String} image
 */
BotMessage.prototype['image'] = undefined;

/**
 * Quick reply buttons
 * @member {Array.<module:model/BotMessageButtons>} buttons
 */
BotMessage.prototype['buttons'] = undefined;

/**
 * Additional information
 * @member {Array.<module:model/BotMessageAttachement>} attachement
 */
BotMessage.prototype['attachement'] = undefined;






export default BotMessage;

