/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BotMessageButtons model module.
 * @module model/BotMessageButtons
 * @version 1.0.0
 */
class BotMessageButtons {
    /**
     * Constructs a new <code>BotMessageButtons</code>.
     * @alias module:model/BotMessageButtons
     */
    constructor() { 
        
        BotMessageButtons.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BotMessageButtons</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BotMessageButtons} obj Optional instance to populate.
     * @return {module:model/BotMessageButtons} The populated <code>BotMessageButtons</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BotMessageButtons();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Button caption
 * @member {String} title
 */
BotMessageButtons.prototype['title'] = undefined;

/**
 * Payload to be sent if button is clicked
 * @member {String} payload
 */
BotMessageButtons.prototype['payload'] = undefined;






export default BotMessageButtons;

