/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConversationStatisticsTopIntents from './ConversationStatisticsTopIntents';

/**
 * The ConversationStatistics model module.
 * @module model/ConversationStatistics
 * @version 1.0.0
 */
class ConversationStatistics {
    /**
     * Constructs a new <code>ConversationStatistics</code>.
     * @alias module:model/ConversationStatistics
     */
    constructor() { 
        
        ConversationStatistics.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConversationStatistics</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConversationStatistics} obj Optional instance to populate.
     * @return {module:model/ConversationStatistics} The populated <code>ConversationStatistics</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConversationStatistics();

            if (data.hasOwnProperty('user_messages')) {
                obj['user_messages'] = ApiClient.convertToType(data['user_messages'], 'Number');
            }
            if (data.hasOwnProperty('bot_messages')) {
                obj['bot_messages'] = ApiClient.convertToType(data['bot_messages'], 'Number');
            }
            if (data.hasOwnProperty('top_intents')) {
                obj['top_intents'] = ApiClient.convertToType(data['top_intents'], [ConversationStatisticsTopIntents]);
            }
            if (data.hasOwnProperty('top_entities')) {
                obj['top_entities'] = ApiClient.convertToType(data['top_entities'], [ConversationStatisticsTopIntents]);
            }
            if (data.hasOwnProperty('top_actions')) {
                obj['top_actions'] = ApiClient.convertToType(data['top_actions'], [ConversationStatisticsTopIntents]);
            }
            if (data.hasOwnProperty('top_policies')) {
                obj['top_policies'] = ApiClient.convertToType(data['top_policies'], [ConversationStatisticsTopIntents]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} user_messages
 */
ConversationStatistics.prototype['user_messages'] = undefined;

/**
 * @member {Number} bot_messages
 */
ConversationStatistics.prototype['bot_messages'] = undefined;

/**
 * @member {Array.<module:model/ConversationStatisticsTopIntents>} top_intents
 */
ConversationStatistics.prototype['top_intents'] = undefined;

/**
 * @member {Array.<module:model/ConversationStatisticsTopIntents>} top_entities
 */
ConversationStatistics.prototype['top_entities'] = undefined;

/**
 * @member {Array.<module:model/ConversationStatisticsTopIntents>} top_actions
 */
ConversationStatistics.prototype['top_actions'] = undefined;

/**
 * @member {Array.<module:model/ConversationStatisticsTopIntents>} top_policies
 */
ConversationStatistics.prototype['top_policies'] = undefined;






export default ConversationStatistics;

