/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FeatureFlag model module.
 * @module model/FeatureFlag
 * @version 1.0.0
 */
class FeatureFlag {
    /**
     * Constructs a new <code>FeatureFlag</code>.
     * Information about a toggable feature
     * @alias module:model/FeatureFlag
     */
    constructor() { 
        
        FeatureFlag.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FeatureFlag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeatureFlag} obj Optional instance to populate.
     * @return {module:model/FeatureFlag} The populated <code>FeatureFlag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeatureFlag();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Name of the feature
 * @member {String} name
 */
FeatureFlag.prototype['name'] = undefined;

/**
 * Is the feature activated
 * @member {Boolean} enabled
 */
FeatureFlag.prototype['enabled'] = undefined;






export default FeatureFlag;

