/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse200Production model module.
 * @module model/InlineResponse200Production
 * @version 1.0.0
 */
class InlineResponse200Production {
    /**
     * Constructs a new <code>InlineResponse200Production</code>.
     * @alias module:model/InlineResponse200Production
     */
    constructor() { 
        
        InlineResponse200Production.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200Production</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse200Production} obj Optional instance to populate.
     * @return {module:model/InlineResponse200Production} The populated <code>InlineResponse200Production</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200Production();

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('minimum_compatible_version')) {
                obj['minimum_compatible_version'] = ApiClient.convertToType(data['minimum_compatible_version'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} version
 */
InlineResponse200Production.prototype['version'] = undefined;

/**
 * @member {String} minimum_compatible_version
 */
InlineResponse200Production.prototype['minimum_compatible_version'] = undefined;

/**
 * @member {Number} status
 */
InlineResponse200Production.prototype['status'] = undefined;






export default InlineResponse200Production;

