/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfstring from './OneOfstring';

/**
 * The InlineResponse404 model module.
 * @module model/InlineResponse404
 * @version 1.0.0
 */
class InlineResponse404 {
    /**
     * Constructs a new <code>InlineResponse404</code>.
     * @alias module:model/InlineResponse404
     */
    constructor() { 
        
        InlineResponse404.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse404</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse404} obj Optional instance to populate.
     * @return {module:model/InlineResponse404} The populated <code>InlineResponse404</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse404();

            if (data.hasOwnProperty('exception')) {
                obj['exception'] = ApiClient.convertToType(data['exception'], 'String');
            }
            if (data.hasOwnProperty('reasons')) {
                obj['reasons'] = ApiClient.convertToType(data['reasons'], OneOfstring);
            }
        }
        return obj;
    }


}

/**
 * @member {String} exception
 */
InlineResponse404.prototype['exception'] = undefined;

/**
 * @member {module:model/OneOfstring} reasons
 */
InlineResponse404.prototype['reasons'] = undefined;






export default InlineResponse404;

