/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject3 model module.
 * @module model/InlineObject3
 * @version 1.0.0
 */
class InlineObject3 {
    /**
     * Constructs a new <code>InlineObject3</code>.
     * @alias module:model/InlineObject3
     * @param username {String} 
     * @param oldPassword {String} 
     * @param newPassword {String} 
     * @param newPasswordConfirm {String} 
     */
    constructor(username, oldPassword, newPassword, newPasswordConfirm) { 
        
        InlineObject3.initialize(this, username, oldPassword, newPassword, newPasswordConfirm);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, oldPassword, newPassword, newPasswordConfirm) { 
        obj['username'] = username;
        obj['old_password'] = oldPassword;
        obj['new_password'] = newPassword;
        obj['new_password_confirm'] = newPasswordConfirm;
    }

    /**
     * Constructs a <code>InlineObject3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject3} obj Optional instance to populate.
     * @return {module:model/InlineObject3} The populated <code>InlineObject3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject3();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('old_password')) {
                obj['old_password'] = ApiClient.convertToType(data['old_password'], 'String');
            }
            if (data.hasOwnProperty('new_password')) {
                obj['new_password'] = ApiClient.convertToType(data['new_password'], 'String');
            }
            if (data.hasOwnProperty('new_password_confirm')) {
                obj['new_password_confirm'] = ApiClient.convertToType(data['new_password_confirm'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
InlineObject3.prototype['username'] = undefined;

/**
 * @member {String} old_password
 */
InlineObject3.prototype['old_password'] = undefined;

/**
 * @member {String} new_password
 */
InlineObject3.prototype['new_password'] = undefined;

/**
 * @member {String} new_password_confirm
 */
InlineObject3.prototype['new_password_confirm'] = undefined;






export default InlineObject3;

