/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProjectsProjectIdDataRasaNluData from './ProjectsProjectIdDataRasaNluData';

/**
 * The InlineObject6 model module.
 * @module model/InlineObject6
 * @version 1.0.0
 */
class InlineObject6 {
    /**
     * Constructs a new <code>InlineObject6</code>.
     * @alias module:model/InlineObject6
     */
    constructor() { 
        
        InlineObject6.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject6</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject6} obj Optional instance to populate.
     * @return {module:model/InlineObject6} The populated <code>InlineObject6</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject6();

            if (data.hasOwnProperty('rasa_nlu_data')) {
                obj['rasa_nlu_data'] = ProjectsProjectIdDataRasaNluData.constructFromObject(data['rasa_nlu_data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ProjectsProjectIdDataRasaNluData} rasa_nlu_data
 */
InlineObject6.prototype['rasa_nlu_data'] = undefined;






export default InlineObject6;

