/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject1 model module.
 * @module model/InlineObject1
 * @version 1.0.0
 */
class InlineObject1 {
    /**
     * Constructs a new <code>InlineObject1</code>.
     * @alias module:model/InlineObject1
     * @param conversationId {String} 
     * @param chatToken {String} 
     */
    constructor(conversationId, chatToken) { 
        
        InlineObject1.initialize(this, conversationId, chatToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, conversationId, chatToken) { 
        obj['conversation_id'] = conversationId;
        obj['chat_token'] = chatToken;
    }

    /**
     * Constructs a <code>InlineObject1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject1} obj Optional instance to populate.
     * @return {module:model/InlineObject1} The populated <code>InlineObject1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject1();

            if (data.hasOwnProperty('conversation_id')) {
                obj['conversation_id'] = ApiClient.convertToType(data['conversation_id'], 'String');
            }
            if (data.hasOwnProperty('chat_token')) {
                obj['chat_token'] = ApiClient.convertToType(data['chat_token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} conversation_id
 */
InlineObject1.prototype['conversation_id'] = undefined;

/**
 * @member {String} chat_token
 */
InlineObject1.prototype['chat_token'] = undefined;






export default InlineObject1;

