/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Intent model module.
 * @module model/Intent
 * @version 1.0.0
 */
class Intent {
    /**
     * Constructs a new <code>Intent</code>.
     * @alias module:model/Intent
     */
    constructor() { 
        
        Intent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Intent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Intent} obj Optional instance to populate.
     * @return {module:model/Intent} The populated <code>Intent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Intent();

            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} confidence
 */
Intent.prototype['confidence'] = undefined;

/**
 * @member {String} name
 */
Intent.prototype['name'] = undefined;






export default Intent;

