/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageWithPredictionUserInputIntent from './MessageWithPredictionUserInputIntent';

/**
 * The MessageWithPredictionUserInput model module.
 * @module model/MessageWithPredictionUserInput
 * @version 1.0.0
 */
class MessageWithPredictionUserInput {
    /**
     * Constructs a new <code>MessageWithPredictionUserInput</code>.
     * @alias module:model/MessageWithPredictionUserInput
     */
    constructor() { 
        
        MessageWithPredictionUserInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessageWithPredictionUserInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageWithPredictionUserInput} obj Optional instance to populate.
     * @return {module:model/MessageWithPredictionUserInput} The populated <code>MessageWithPredictionUserInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageWithPredictionUserInput();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('intent')) {
                obj['intent'] = MessageWithPredictionUserInputIntent.constructFromObject(data['intent']);
            }
            if (data.hasOwnProperty('entities')) {
                obj['entities'] = ApiClient.convertToType(data['entities'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} text
 */
MessageWithPredictionUserInput.prototype['text'] = undefined;

/**
 * @member {module:model/MessageWithPredictionUserInputIntent} intent
 */
MessageWithPredictionUserInput.prototype['intent'] = undefined;

/**
 * @member {Array.<Object>} entities
 */
MessageWithPredictionUserInput.prototype['entities'] = undefined;






export default MessageWithPredictionUserInput;

