/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MismatchWarning model module.
 * @module model/MismatchWarning
 * @version 1.0.0
 */
class MismatchWarning {
    /**
     * Constructs a new <code>MismatchWarning</code>.
     * Mismatch warning of domain items that are either found in the domain or in training data, but not in both
     * @alias module:model/MismatchWarning
     */
    constructor() { 
        
        MismatchWarning.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MismatchWarning</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MismatchWarning} obj Optional instance to populate.
     * @return {module:model/MismatchWarning} The populated <code>MismatchWarning</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MismatchWarning();

            if (data.hasOwnProperty('in_training_data')) {
                obj['in_training_data'] = ApiClient.convertToType(data['in_training_data'], ['String']);
            }
            if (data.hasOwnProperty('in_domain')) {
                obj['in_domain'] = ApiClient.convertToType(data['in_domain'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} in_training_data
 */
MismatchWarning.prototype['in_training_data'] = undefined;

/**
 * @member {Array.<String>} in_domain
 */
MismatchWarning.prototype['in_domain'] = undefined;






export default MismatchWarning;

