/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NlgRequest model module.
 * @module model/NlgRequest
 * @version 1.0.0
 */
class NlgRequest {
    /**
     * Constructs a new <code>NlgRequest</code>.
     * Request object for NLG
     * @alias module:model/NlgRequest
     */
    constructor() { 
        
        NlgRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NlgRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NlgRequest} obj Optional instance to populate.
     * @return {module:model/NlgRequest} The populated <code>NlgRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NlgRequest();

            if (data.hasOwnProperty('tracker')) {
                obj['tracker'] = ApiClient.convertToType(data['tracker'], Object);
            }
            if (data.hasOwnProperty('arguments')) {
                obj['arguments'] = ApiClient.convertToType(data['arguments'], Object);
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = ApiClient.convertToType(data['template'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} tracker
 */
NlgRequest.prototype['tracker'] = undefined;

/**
 * @member {Object} arguments
 */
NlgRequest.prototype['arguments'] = undefined;

/**
 * @member {String} template
 */
NlgRequest.prototype['template'] = undefined;

/**
 * @member {Object} channel
 */
NlgRequest.prototype['channel'] = undefined;






export default NlgRequest;

