/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NlgResponse model module.
 * @module model/NlgResponse
 * @version 1.0.0
 */
class NlgResponse {
    /**
     * Constructs a new <code>NlgResponse</code>.
     * Generated bot response
     * @alias module:model/NlgResponse
     * @param text {String} 
     * @param template {String} 
     */
    constructor(text, template) { 
        
        NlgResponse.initialize(this, text, template);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, text, template) { 
        obj['text'] = text;
        obj['template'] = template;
    }

    /**
     * Constructs a <code>NlgResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NlgResponse} obj Optional instance to populate.
     * @return {module:model/NlgResponse} The populated <code>NlgResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NlgResponse();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('buttons')) {
                obj['buttons'] = ApiClient.convertToType(data['buttons'], ['String']);
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('elements')) {
                obj['elements'] = ApiClient.convertToType(data['elements'], ['String']);
            }
            if (data.hasOwnProperty('attachment')) {
                obj['attachment'] = ApiClient.convertToType(data['attachment'], 'String');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = ApiClient.convertToType(data['template'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} text
 */
NlgResponse.prototype['text'] = undefined;

/**
 * @member {Array.<String>} buttons
 */
NlgResponse.prototype['buttons'] = undefined;

/**
 * @member {String} image
 */
NlgResponse.prototype['image'] = undefined;

/**
 * @member {Array.<String>} elements
 */
NlgResponse.prototype['elements'] = undefined;

/**
 * @member {String} attachment
 */
NlgResponse.prototype['attachment'] = undefined;

/**
 * @member {String} template
 */
NlgResponse.prototype['template'] = undefined;

/**
 * @member {String} id
 */
NlgResponse.prototype['id'] = undefined;






export default NlgResponse;

