/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Conversation from './Conversation';
import PredictResultScores from './PredictResultScores';

/**
 * The PredictResult model module.
 * @module model/PredictResult
 * @version 1.0.0
 */
class PredictResult {
    /**
     * Constructs a new <code>PredictResult</code>.
     * @alias module:model/PredictResult
     */
    constructor() { 
        
        PredictResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PredictResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PredictResult} obj Optional instance to populate.
     * @return {module:model/PredictResult} The populated <code>PredictResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PredictResult();

            if (data.hasOwnProperty('scores')) {
                obj['scores'] = ApiClient.convertToType(data['scores'], [PredictResultScores]);
            }
            if (data.hasOwnProperty('policy')) {
                obj['policy'] = ApiClient.convertToType(data['policy'], 'String');
            }
            if (data.hasOwnProperty('tracker')) {
                obj['tracker'] = Conversation.constructFromObject(data['tracker']);
            }
        }
        return obj;
    }


}

/**
 * Prediction results
 * @member {Array.<module:model/PredictResultScores>} scores
 */
PredictResult.prototype['scores'] = undefined;

/**
 * Policy which predicted the most likely action
 * @member {String} policy
 */
PredictResult.prototype['policy'] = undefined;

/**
 * @member {module:model/Conversation} tracker
 */
PredictResult.prototype['tracker'] = undefined;






export default PredictResult;

