/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PredictResultScores model module.
 * @module model/PredictResultScores
 * @version 1.0.0
 */
class PredictResultScores {
    /**
     * Constructs a new <code>PredictResultScores</code>.
     * @alias module:model/PredictResultScores
     */
    constructor() { 
        
        PredictResultScores.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PredictResultScores</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PredictResultScores} obj Optional instance to populate.
     * @return {module:model/PredictResultScores} The populated <code>PredictResultScores</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PredictResultScores();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Action name
 * @member {String} action
 */
PredictResultScores.prototype['action'] = undefined;

/**
 * Assigned score
 * @member {Number} score
 */
PredictResultScores.prototype['score'] = undefined;






export default PredictResultScores;

