/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrainingExample from './TrainingExample';

/**
 * The ProjectsProjectIdDataRasaNluData model module.
 * @module model/ProjectsProjectIdDataRasaNluData
 * @version 1.0.0
 */
class ProjectsProjectIdDataRasaNluData {
    /**
     * Constructs a new <code>ProjectsProjectIdDataRasaNluData</code>.
     * @alias module:model/ProjectsProjectIdDataRasaNluData
     */
    constructor() { 
        
        ProjectsProjectIdDataRasaNluData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProjectsProjectIdDataRasaNluData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectsProjectIdDataRasaNluData} obj Optional instance to populate.
     * @return {module:model/ProjectsProjectIdDataRasaNluData} The populated <code>ProjectsProjectIdDataRasaNluData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectsProjectIdDataRasaNluData();

            if (data.hasOwnProperty('common_examples')) {
                obj['common_examples'] = ApiClient.convertToType(data['common_examples'], [TrainingExample]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TrainingExample>} common_examples
 */
ProjectsProjectIdDataRasaNluData.prototype['common_examples'] = undefined;






export default ProjectsProjectIdDataRasaNluData;

