/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RasaCoreStoryObjectAnnotation from './RasaCoreStoryObjectAnnotation';

/**
 * The RasaCoreStoryObject model module.
 * @module model/RasaCoreStoryObject
 * @version 1.0.0
 */
class RasaCoreStoryObject {
    /**
     * Constructs a new <code>RasaCoreStoryObject</code>.
     * @alias module:model/RasaCoreStoryObject
     */
    constructor() { 
        
        RasaCoreStoryObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RasaCoreStoryObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RasaCoreStoryObject} obj Optional instance to populate.
     * @return {module:model/RasaCoreStoryObject} The populated <code>RasaCoreStoryObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RasaCoreStoryObject();

            if (data.hasOwnProperty('story')) {
                obj['story'] = ApiClient.convertToType(data['story'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('annotation')) {
                obj['annotation'] = RasaCoreStoryObjectAnnotation.constructFromObject(data['annotation']);
            }
        }
        return obj;
    }


}

/**
 * Rasa Core story in Markdown format
 * @member {String} story
 */
RasaCoreStoryObject.prototype['story'] = undefined;

/**
 * @member {String} id
 */
RasaCoreStoryObject.prototype['id'] = undefined;

/**
 * @member {module:model/RasaCoreStoryObjectAnnotation} annotation
 */
RasaCoreStoryObject.prototype['annotation'] = undefined;






export default RasaCoreStoryObject;

