/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestartEvent model module.
 * @module model/RestartEvent
 * @version 1.0.0
 */
class RestartEvent {
    /**
     * Constructs a new <code>RestartEvent</code>.
     * @alias module:model/RestartEvent
     */
    constructor() { 
        
        RestartEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestartEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestartEvent} obj Optional instance to populate.
     * @return {module:model/RestartEvent} The populated <code>RestartEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestartEvent();

            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RestartEvent.EventEnum} event
 */
RestartEvent.prototype['event'] = undefined;

/**
 * @member {Number} timestamp
 */
RestartEvent.prototype['timestamp'] = undefined;





/**
 * Allowed values for the <code>event</code> property.
 * @enum {String}
 * @readonly
 */
RestartEvent['EventEnum'] = {

    /**
     * value: "restart"
     * @const
     */
    "restart": "restart"
};



export default RestartEvent;

