/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RolesRoleGrants model module.
 * @module model/RolesRoleGrants
 * @version 1.0.0
 */
class RolesRoleGrants {
    /**
     * Constructs a new <code>RolesRoleGrants</code>.
     * @alias module:model/RolesRoleGrants
     */
    constructor() { 
        
        RolesRoleGrants.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RolesRoleGrants</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RolesRoleGrants} obj Optional instance to populate.
     * @return {module:model/RolesRoleGrants} The populated <code>RolesRoleGrants</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RolesRoleGrants();

            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ApiClient.convertToType(data['actions'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} category
 */
RolesRoleGrants.prototype['category'] = undefined;

/**
 * @member {Array.<String>} actions
 */
RolesRoleGrants.prototype['actions'] = undefined;






export default RolesRoleGrants;

