/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RoleGrants model module.
 * @module model/RoleGrants
 * @version 1.0.0
 */
class RoleGrants {
    /**
     * Constructs a new <code>RoleGrants</code>.
     * @alias module:model/RoleGrants
     */
    constructor() { 
        
        RoleGrants.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RoleGrants</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RoleGrants} obj Optional instance to populate.
     * @return {module:model/RoleGrants} The populated <code>RoleGrants</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoleGrants();

            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} category
 */
RoleGrants.prototype['category'] = undefined;






export default RoleGrants;

