/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfstringinteger from './OneOfstringinteger';

/**
 * The TrainingExampleEntities model module.
 * @module model/TrainingExampleEntities
 * @version 1.0.0
 */
class TrainingExampleEntities {
    /**
     * Constructs a new <code>TrainingExampleEntities</code>.
     * @alias module:model/TrainingExampleEntities
     * @param start {module:model/OneOfstringinteger} 
     * @param end {module:model/OneOfstringinteger} 
     * @param entity {module:model/OneOfstringinteger} 
     * @param value {module:model/OneOfstringinteger} 
     */
    constructor(start, end, entity, value) { 
        
        TrainingExampleEntities.initialize(this, start, end, entity, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, start, end, entity, value) { 
        obj['start'] = start;
        obj['end'] = end;
        obj['entity'] = entity;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>TrainingExampleEntities</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrainingExampleEntities} obj Optional instance to populate.
     * @return {module:model/TrainingExampleEntities} The populated <code>TrainingExampleEntities</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingExampleEntities();

            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], OneOfstringinteger);
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], OneOfstringinteger);
            }
            if (data.hasOwnProperty('entity')) {
                obj['entity'] = ApiClient.convertToType(data['entity'], OneOfstringinteger);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], OneOfstringinteger);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OneOfstringinteger} start
 */
TrainingExampleEntities.prototype['start'] = undefined;

/**
 * @member {module:model/OneOfstringinteger} end
 */
TrainingExampleEntities.prototype['end'] = undefined;

/**
 * @member {module:model/OneOfstringinteger} entity
 */
TrainingExampleEntities.prototype['entity'] = undefined;

/**
 * @member {module:model/OneOfstringinteger} value
 */
TrainingExampleEntities.prototype['value'] = undefined;






export default TrainingExampleEntities;

