/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParseData from './ParseData';

/**
 * The UserEvent model module.
 * @module model/UserEvent
 * @version 1.0.0
 */
class UserEvent {
    /**
     * Constructs a new <code>UserEvent</code>.
     * @alias module:model/UserEvent
     */
    constructor() { 
        
        UserEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserEvent} obj Optional instance to populate.
     * @return {module:model/UserEvent} The populated <code>UserEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserEvent();

            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('parse_data')) {
                obj['parse_data'] = ParseData.constructFromObject(data['parse_data']);
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('is_flagged')) {
                obj['is_flagged'] = ApiClient.convertToType(data['is_flagged'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UserEvent.EventEnum} event
 */
UserEvent.prototype['event'] = undefined;

/**
 * @member {module:model/ParseData} parse_data
 */
UserEvent.prototype['parse_data'] = undefined;

/**
 * @member {String} text
 */
UserEvent.prototype['text'] = undefined;

/**
 * @member {Number} timestamp
 */
UserEvent.prototype['timestamp'] = undefined;

/**
 * True if message was flagged.
 * @member {Boolean} is_flagged
 * @default false
 */
UserEvent.prototype['is_flagged'] = false;





/**
 * Allowed values for the <code>event</code> property.
 * @enum {String}
 * @readonly
 */
UserEvent['EventEnum'] = {

    /**
     * value: "user"
     * @const
     */
    "user": "user"
};



export default UserEvent;

