/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ConversationStatistics from '../model/ConversationStatistics';

/**
* Analyics service.
* @module api/AnalyicsApi
* @version 1.0.0
*/
export default class AnalyicsApi {

    /**
    * Constructs a new AnalyicsApi. 
    * @alias module:api/AnalyicsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getConversationStatistics operation.
     * @callback module:api/AnalyicsApi~getConversationStatisticsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ConversationStatistics} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch conversation statistics
     * @param {module:api/AnalyicsApi~getConversationStatisticsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ConversationStatistics}
     */
    getConversationStatistics(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ConversationStatistics;
      return this.apiClient.callApi(
        '/statistics', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
