/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PredictResult from '../model/PredictResult';

/**
* Evaluation service.
* @module api/EvaluationApi
* @version 1.0.0
*/
export default class EvaluationApi {

    /**
    * Constructs a new EvaluationApi. 
    * @alias module:api/EvaluationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the predictNextAction operation.
     * @callback module:api/EvaluationApi~predictNextActionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PredictResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Predicts the next action in the conversation.
     * @param {String} conversationId Sender ID
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.includeEvents  (default to 'ALL')
     * @param {module:api/EvaluationApi~predictNextActionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PredictResult}
     */
    predictNextAction(conversationId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'conversationId' is set
      if (conversationId === undefined || conversationId === null) {
        throw new Error("Missing the required parameter 'conversationId' when calling predictNextAction");
      }

      let pathParams = {
        'conversation_id': conversationId
      };
      let queryParams = {
        'include_events': opts['includeEvents']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PredictResult;
      return this.apiClient.callApi(
        '/conversations/{conversation_id}/predict', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
