/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RasaXHttpApi);
  }
}(this, function(expect, RasaXHttpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RasaXHttpApi.AnalyticsResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnalyticsResult', function() {
    it('should create an instance of AnalyticsResult', function() {
      // uncomment below and update the code to test AnalyticsResult
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be.a(RasaXHttpApi.AnalyticsResult);
    });

    it('should have the property binCenters (base name: "bin_centers")', function() {
      // uncomment below and update the code to test the property binCenters
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

    it('should have the property binWidth (base name: "bin_width")', function() {
      // uncomment below and update the code to test the property binWidth
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

    it('should have the property newUsers (base name: "new_users")', function() {
      // uncomment below and update the code to test the property newUsers
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

    it('should have the property conversations (base name: "conversations")', function() {
      // uncomment below and update the code to test the property conversations
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

    it('should have the property userMessages (base name: "user_messages")', function() {
      // uncomment below and update the code to test the property userMessages
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

    it('should have the property botMessages (base name: "bot_messages")', function() {
      // uncomment below and update the code to test the property botMessages
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

    it('should have the property totalMessages (base name: "total_messages")', function() {
      // uncomment below and update the code to test the property totalMessages
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

    it('should have the property sessionsPerUser (base name: "sessions_per_user")', function() {
      // uncomment below and update the code to test the property sessionsPerUser
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

    it('should have the property conversationLength (base name: "conversation_length")', function() {
      // uncomment below and update the code to test the property conversationLength
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

    it('should have the property conversationSteps (base name: "conversation_steps")', function() {
      // uncomment below and update the code to test the property conversationSteps
      //var instane = new RasaXHttpApi.AnalyticsResult();
      //expect(instance).to.be();
    });

  });

}));
