/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RasaXHttpApi);
  }
}(this, function(expect, RasaXHttpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RasaXHttpApi.Conversation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Conversation', function() {
    it('should create an instance of Conversation', function() {
      // uncomment below and update the code to test Conversation
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be.a(RasaXHttpApi.Conversation);
    });

    it('should have the property conversationId (base name: "conversation_id")', function() {
      // uncomment below and update the code to test the property conversationId
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property latestEventTime (base name: "latest_event_time")', function() {
      // uncomment below and update the code to test the property latestEventTime
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property events (base name: "events")', function() {
      // uncomment below and update the code to test the property events
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property latestMessage (base name: "latest_message")', function() {
      // uncomment below and update the code to test the property latestMessage
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property paused (base name: "paused")', function() {
      // uncomment below and update the code to test the property paused
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property followupAction (base name: "followup_action")', function() {
      // uncomment below and update the code to test the property followupAction
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property slots (base name: "slots")', function() {
      // uncomment below and update the code to test the property slots
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property latestInputChannel (base name: "latest_input_channel")', function() {
      // uncomment below and update the code to test the property latestInputChannel
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property latestActionName (base name: "latest_action_name")', function() {
      // uncomment below and update the code to test the property latestActionName
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property activeForm (base name: "active_form")', function() {
      // uncomment below and update the code to test the property activeForm
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property flaggedMessages (base name: "flagged_messages")', function() {
      // uncomment below and update the code to test the property flaggedMessages
      //var instane = new RasaXHttpApi.Conversation();
      //expect(instance).to.be();
    });

  });

}));
