/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RasaXHttpApi);
  }
}(this, function(expect, RasaXHttpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RasaXHttpApi.ConversationStatistics();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConversationStatistics', function() {
    it('should create an instance of ConversationStatistics', function() {
      // uncomment below and update the code to test ConversationStatistics
      //var instane = new RasaXHttpApi.ConversationStatistics();
      //expect(instance).to.be.a(RasaXHttpApi.ConversationStatistics);
    });

    it('should have the property userMessages (base name: "user_messages")', function() {
      // uncomment below and update the code to test the property userMessages
      //var instane = new RasaXHttpApi.ConversationStatistics();
      //expect(instance).to.be();
    });

    it('should have the property botMessages (base name: "bot_messages")', function() {
      // uncomment below and update the code to test the property botMessages
      //var instane = new RasaXHttpApi.ConversationStatistics();
      //expect(instance).to.be();
    });

    it('should have the property topIntents (base name: "top_intents")', function() {
      // uncomment below and update the code to test the property topIntents
      //var instane = new RasaXHttpApi.ConversationStatistics();
      //expect(instance).to.be();
    });

    it('should have the property topEntities (base name: "top_entities")', function() {
      // uncomment below and update the code to test the property topEntities
      //var instane = new RasaXHttpApi.ConversationStatistics();
      //expect(instance).to.be();
    });

    it('should have the property topActions (base name: "top_actions")', function() {
      // uncomment below and update the code to test the property topActions
      //var instane = new RasaXHttpApi.ConversationStatistics();
      //expect(instance).to.be();
    });

    it('should have the property topPolicies (base name: "top_policies")', function() {
      // uncomment below and update the code to test the property topPolicies
      //var instane = new RasaXHttpApi.ConversationStatistics();
      //expect(instance).to.be();
    });

  });

}));
