/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RasaXHttpApi);
  }
}(this, function(expect, RasaXHttpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RasaXHttpApi.IntentInformation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IntentInformation', function() {
    it('should create an instance of IntentInformation', function() {
      // uncomment below and update the code to test IntentInformation
      //var instane = new RasaXHttpApi.IntentInformation();
      //expect(instance).to.be.a(RasaXHttpApi.IntentInformation);
    });

    it('should have the property intent (base name: "intent")', function() {
      // uncomment below and update the code to test the property intent
      //var instane = new RasaXHttpApi.IntentInformation();
      //expect(instance).to.be();
    });

    it('should have the property exampleHashes (base name: "example_hashes")', function() {
      // uncomment below and update the code to test the property exampleHashes
      //var instane = new RasaXHttpApi.IntentInformation();
      //expect(instance).to.be();
    });

    it('should have the property suggestions (base name: "suggestions")', function() {
      // uncomment below and update the code to test the property suggestions
      //var instane = new RasaXHttpApi.IntentInformation();
      //expect(instance).to.be();
    });

    it('should have the property isTemporaray (base name: "is_temporaray")', function() {
      // uncomment below and update the code to test the property isTemporaray
      //var instane = new RasaXHttpApi.IntentInformation();
      //expect(instance).to.be();
    });

    it('should have the property mappedTo (base name: "mapped_to")', function() {
      // uncomment below and update the code to test the property mappedTo
      //var instane = new RasaXHttpApi.IntentInformation();
      //expect(instance).to.be();
    });

    it('should have the property userGoal (base name: "user_goal")', function() {
      // uncomment below and update the code to test the property userGoal
      //var instane = new RasaXHttpApi.IntentInformation();
      //expect(instance).to.be();
    });

  });

}));
