/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RasaXHttpApi);
  }
}(this, function(expect, RasaXHttpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RasaXHttpApi.ModelsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModelsApi', function() {
    describe('getModels', function() {
      it('should call getModels successfully', function(done) {
        //uncomment below and update the code to test getModels
        //instance.getModels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectsProjectIdModelsModelDelete', function() {
      it('should call projectsProjectIdModelsModelDelete successfully', function(done) {
        //uncomment below and update the code to test projectsProjectIdModelsModelDelete
        //instance.projectsProjectIdModelsModelDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectsProjectIdModelsModelTagsTagDelete', function() {
      it('should call projectsProjectIdModelsModelTagsTagDelete successfully', function(done) {
        //uncomment below and update the code to test projectsProjectIdModelsModelTagsTagDelete
        //instance.projectsProjectIdModelsModelTagsTagDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectsProjectIdModelsModelTagsTagPut', function() {
      it('should call projectsProjectIdModelsModelTagsTagPut successfully', function(done) {
        //uncomment below and update the code to test projectsProjectIdModelsModelTagsTagPut
        //instance.projectsProjectIdModelsModelTagsTagPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectsProjectIdModelsPost', function() {
      it('should call projectsProjectIdModelsPost successfully', function(done) {
        //uncomment below and update the code to test projectsProjectIdModelsPost
        //instance.projectsProjectIdModelsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectsProjectIdModelsTagsTagGet', function() {
      it('should call projectsProjectIdModelsTagsTagGet successfully', function(done) {
        //uncomment below and update the code to test projectsProjectIdModelsTagsTagGet
        //instance.projectsProjectIdModelsTagsTagGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
