/**
 * Rasa X HTTP API
 * This is the Rasa X HTTP API 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RasaXHttpApi);
  }
}(this, function(expect, RasaXHttpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RasaXHttpApi.NLUDataApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NLUDataApi', function() {
    describe('addData', function() {
      it('should call addData successfully', function(done) {
        //uncomment below and update the code to test addData
        //instance.addData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteData', function() {
      it('should call deleteData successfully', function(done) {
        //uncomment below and update the code to test deleteData
        //instance.deleteData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getData', function() {
      it('should call getData successfully', function(done) {
        //uncomment below and update the code to test getData
        //instance.getData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDataJson', function() {
      it('should call getDataJson successfully', function(done) {
        //uncomment below and update the code to test getDataJson
        //instance.getDataJson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDataWarnings', function() {
      it('should call getDataWarnings successfully', function(done) {
        //uncomment below and update the code to test getDataWarnings
        //instance.getDataWarnings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEntities', function() {
      it('should call getEntities successfully', function(done) {
        //uncomment below and update the code to test getEntities
        //instance.getEntities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceBulkData', function() {
      it('should call replaceBulkData successfully', function(done) {
        //uncomment below and update the code to test replaceBulkData
        //instance.replaceBulkData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateExample', function() {
      it('should call updateExample successfully', function(done) {
        //uncomment below and update the code to test updateExample
        //instance.updateExample(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateExampleById', function() {
      it('should call updateExampleById successfully', function(done) {
        //uncomment below and update the code to test updateExampleById
        //instance.updateExampleById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
